#!/system/bin/sh
function hide() {
#locate the files
INIT_LOC=`which su`
if [ ! "$INIT_LOC" ]
then
	echo "cannot find"
	exit 1
else
	#just to double check it's magi
	MTEST=`ls -l $INIT_LOC`
	if [[ $MTEST = *magi* ]]
	then
		BASE_DIR=${INIT_LOC/su/}
		MIDE_DIR="${BASE_DIR}mide"
	else
		echo "not a magi"
		exit 1
	fi
fi
#array to remove
RMARR=(.core magiskhide magiskpolicy resetprop su supolicy)
for i in "${RMARR[@]}"
do
	rm "${BASE_DIR}${i}"
done

mkdir $MIDE_DIR
#array to move
MVARR=(.magisk magisk magiskinit)
for i in "${MVARR[@]}"
do
	mv "${BASE_DIR}${i}" $MIDE_DIR
done
echo "Hidden."
exit 0
}

function unhide() {	
BASE_DIR="/sbin/"
MIDE_DIR="/sbin/mide"
MVARR=(.magisk magisk magiskinit)
for i in "${MVARR[@]}"
do
	mv "${MIDE_DIR}/${i}" $BASE_DIR
done
rmdir $MIDE_DIR

ln -s "${BASE_DIR}.magisk" "${BASE_DIR}.core"

MLARR=(magiskhide resetprop su)
for i in "${MLARR[@]}"
do
	ln -s "${BASE_DIR}magisk" "${BASE_DIR}${i}"
done

MILARR=(magiskpolicy supolicy)
for i in "${MILARR[@]}"
do
	ln -s "${BASE_DIR}magiskinit" "${BASE_DIR}${i}"
done
echo "Restored successfully."
exit 0
}
case "$1" in
	"hide") 
	echo "Hiding..."
	hide
	;;
	"unhide") 
	echo "Unhiding..."
	unhide
	;;
	*)
	echo "Usage:"
	echo "${0} hide - hides..."
	echo "${0} unhide - unhides..."
	echo "note that hiding and unhiding requires a privleged session"
	exit 0
	;;
esac